services:
  ros:
    build:
      context: .
      args:
        WITH_F1TENTH_GYM: "1"
    depends_on:
      - novnc
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    volumes:
      - ./src:/home/developer/sim_ws/src

  # https://github.com/theasp/docker-novnc
  novnc:
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    image: theasp/novnc:latest
    networks:
      - x11
    ports:
      - "8080:8080"

networks:
  x11:
